# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

# optional port (defaults to 4242)
port = 4242
# # optional frontend -> defaults to gtk if available
# # possible values are "cli" and "gtk" 
frontend = "cli"

[right]
hostname = "fejiberglibstein"
activate_on_startup = true

[left]
hostname = "alaptopt"
activate_on_startup = true
